<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipalities = [
            ['municipality_name' => 'Agua de Dios'],
            ['municipality_name' => 'Albán'],
            ['municipality_name' => 'Anapoima'],
            ['municipality_name' => 'Anolaima'],
            ['municipality_name' => 'Apulo'],
            ['municipality_name' => 'Arbeláez'],
            ['municipality_name' => 'Beltrán'],
            ['municipality_name' => 'Bituima'],
            ['municipality_name' => 'Bojacá'],
            ['municipality_name' => 'Cabrera'],
            ['municipality_name' => 'Cachipay'],
            ['municipality_name' => 'Cajicá'],
            ['municipality_name' => 'Caparrapí'],
            ['municipality_name' => 'Cáqueza'],
            ['municipality_name' => 'Carmen de Carupa'],
            ['municipality_name' => 'Chaguaní'],
            ['municipality_name' => 'Chía'],
            ['municipality_name' => 'Chipaque'],
            ['municipality_name' => 'Choachí'],
            ['municipality_name' => 'Chocontá'],
            ['municipality_name' => 'Cogua'],
            ['municipality_name' => 'Cota'],
            ['municipality_name' => 'Cucunubá'],
            ['municipality_name' => 'El Colegio'],
            ['municipality_name' => 'El Peñón'],
            ['municipality_name' => 'El Rosal'],
            ['municipality_name' => 'Facatativá'],
            ['municipality_name' => 'Fomeque'],
            ['municipality_name' => 'Fosca'],
            ['municipality_name' => 'Funza'],
            ['municipality_name' => 'Fúquene'],
            ['municipality_name' => 'Fusagasugá'],
            ['municipality_name' => 'Gachalá'],
            ['municipality_name' => 'Gachancipá'],
            ['municipality_name' => 'Gachetá'],
            ['municipality_name' => 'Gama'],
            ['municipality_name' => 'Girardot'],
            ['municipality_name' => 'Granada'],
            ['municipality_name' => 'Guachetá'],
            ['municipality_name' => 'Guaduas'],
            ['municipality_name' => 'Guasca'],
            ['municipality_name' => 'Guataquí'],
            ['municipality_name' => 'Guatavita'],
            ['municipality_name' => 'Guayabal de Síquima'],
            ['municipality_name' => 'Guayabetal'],
            ['municipality_name' => 'Gutiérrez'],
            ['municipality_name' => 'Jerusalén'],
            ['municipality_name' => 'Junín'],
            ['municipality_name' => 'La Calera'],
            ['municipality_name' => 'La Mesa'],
            ['municipality_name' => 'La Palma'],
            ['municipality_name' => 'La Peña'],
            ['municipality_name' => 'La Vega'],
            ['municipality_name' => 'Lenguazaque'],
            ['municipality_name' => 'Machetá'],
            ['municipality_name' => 'Madrid'],
            ['municipality_name' => 'Manta'],
            ['municipality_name' => 'Medina'],
            ['municipality_name' => 'Mosquera'],
            ['municipality_name' => 'Nariño'],
            ['municipality_name' => 'Nemocón'],
            ['municipality_name' => 'Nilo'],
            ['municipality_name' => 'Nimaima'],
            ['municipality_name' => 'Nocaima'],
            ['municipality_name' => 'Pacho'],
            ['municipality_name' => 'Paime'],
            ['municipality_name' => 'Pandi'],
            ['municipality_name' => 'Paratebueno'],
            ['municipality_name' => 'Pasca'],
            ['municipality_name' => 'Puerto Salgar'],
            ['municipality_name' => 'Pulí'],
            ['municipality_name' => 'Quebradanegra'],
            ['municipality_name' => 'Quetame'],
            ['municipality_name' => 'Quipile'],
            ['municipality_name' => 'Ricaurte'],
            ['municipality_name' => 'San Antonio del Tequendama'],
            ['municipality_name' => 'San Bernardo'],
            ['municipality_name' => 'San Cayetano'],
            ['municipality_name' => 'San Francisco'],
            ['municipality_name' => 'San Juan de Río Seco'],
            ['municipality_name' => 'Sasaima'],
            ['municipality_name' => 'Sesquilé'],
            ['municipality_name' => 'Sibaté'],
            ['municipality_name' => 'Silvania'],
            ['municipality_name' => 'Simijaca'],
            ['municipality_name' => 'Soacha'],
            ['municipality_name' => 'Sopó'],
            ['municipality_name' => 'Subachoque'],
            ['municipality_name' => 'Suesca'],
            ['municipality_name' => 'Supatá'],
            ['municipality_name' => 'Susa'],
            ['municipality_name' => 'Sutatausa'],
            ['municipality_name' => 'Tabio'],
            ['municipality_name' => 'Tausa'],
            ['municipality_name' => 'Tena'],
            ['municipality_name' => 'Tenjo'],
            ['municipality_name' => 'Tibacuy'],
            ['municipality_name' => 'Tibirita'],
            ['municipality_name' => 'Tocaima'],
            ['municipality_name' => 'Tocancipá'],
            ['municipality_name' => 'Topaipí'],
            ['municipality_name' => 'Ubalá'],
            ['municipality_name' => 'Ubaque'],
            ['municipality_name' => 'Ubaté'],
            ['municipality_name' => 'Une'],
            ['municipality_name' => 'Útica'],
            ['municipality_name' => 'Venecia'],
            ['municipality_name' => 'Vergara'],
            ['municipality_name' => 'Vianí'],
            ['municipality_name' => 'Villagómez'],
            ['municipality_name' => 'Villapinzón'],
            ['municipality_name' => 'Villeta'],
            ['municipality_name' => 'Viotá'],
            ['municipality_name' => 'Yacopí'],
            ['municipality_name' => 'Zipacón'],
            ['municipality_name' => 'Zipaquirá'],
        ];

        DB::table('municipalities')->insert($municipalities);
    }
}
