<h1>HOLAAAAAA</h1>

<p>ARREGLAR ESTILOS, AGREGAR FALTANTES, REALIZAR LAS POSTULACIONES Y DEMAS FUNCIONES
    HOY REALICE LOS REQUEST POR CADA TABLA, CABE RECALCAR QUE NO ESTAN TODAS, TRATE DE REALIZAR LA BIENVENIDA POR MEDIO DE CORREO, NO DEJA REALIZARLA, EL CONTROLADOR REGISTER NO ESTABA HACIENDO NADA PERO LO DEJE AHI HICE ARREGLOS CSS Y HASTA AHORA ESO.
</p>